### ISSUE TITLE
Permissão negada na pasta dist

### ISSUE THREAD

**Issue by henriqdev** [codeedu/nodejs-rabbitmq-sample#1]
Estou tentando replicar o exemplo, utilizando apenas a conexão api NEST e RabbitMQ porem retorna esse erro quando eu levanto o docker-compose.
![image](https://user-images.githubusercontent.com/45500117/144911733-d2e69945-45b5-4822-9f2e-db947e2820a7.png)
acredito que posso ser por causa do link "amqp://user:password@url>port" quando mexo nela o erro ñ da de cara mais da acesso negado a fila. esse erro
![image](https://user-images.githubusercontent.com/45500117/144912108-a8ce4aa1-8a9f-4a90-96aa-c2a7e1ae37ea.png)

minha função post se encontra assim.
![image](https://user-images.githubusercontent.com/45500117/144912234-a8ca0b13-c408-44f9-8766-c6d3700f12ba.png)
onde eu poderia esta errando alguém teria alguma noção? grato desde já

**Comment by argentinaluiz** [comment]
Olá @henriqdev , tudo bem?

Execute o comando no seu terminal `id -u SEU_USER`. Isto mostrará qual é o ID do seu usuário. 

Neste exemplo, ambas as aplicações Nest.js e Express usam o usuário `node` na imagem Docker, este usuário tem ID 1000, se seu usuário não tiver ID 1000, não equivalerá as permissões e dará este erro. Neste caso, é necessário converter o usuário `node` para o seu ID usando o comando `usermod` dentro do Dockerfile.

**Comment by henriqdev** [comment]
Desculpa ñ responder antes, era exatamente isso obrigado rs
